/**
 * Fixed-input generator: turns the pinned provider JSON Schema (2020-12
 * subset used by admin-dashboard/v1) into generated Zod validators. Every
 * field in the generated output is derived from the schema — nothing here
 * hand-invents or widens a field.
 */
type ObjectBranch = { properties: Record<string, JsonSchema>; required?: readonly string[] };

export type JsonSchema =
  | { const: string | boolean | null }
  | { enum: readonly string[] }
  | { type: "string"; format?: string }
  | { type: "integer"; minimum?: number }
  | { type: "array"; items: JsonSchema; maxItems?: number }
  | {
      type: "object";
      properties?: Record<string, JsonSchema>;
      required?: readonly string[];
      additionalProperties?: false;
      unevaluatedProperties?: false;
      oneOf?: readonly ObjectBranch[];
    }
  | { oneOf: readonly JsonSchema[] };

function branchName(branch: JsonSchema): string {
  if (!("type" in branch) || branch.type !== "object") {
    return "contract";
  }
  const report = branch.properties?.report;
  if (report && "const" in report && typeof report.const === "string") {
    return `${report.const}Report`;
  }
  if (branch.properties && "authorized" in branch.properties) {
    return "authorization";
  }
  return "contract";
}

function objectExpression(properties: Record<string, JsonSchema>, required: readonly string[], strict: boolean): string {
  const requiredSet = new Set(required);
  const fields = Object.entries(properties)
    .map(([key, value]) => {
      const expression = toZodExpression(value);
      return `  ${key}: ${requiredSet.has(key) ? expression : `${expression}.optional()`},`;
    })
    .join("\n");
  return `z.object({\n${fields}\n})${strict ? ".strict()" : ""}`;
}

function toZodExpression(schema: JsonSchema): string {
  if ("const" in schema) {
    return `z.literal(${JSON.stringify(schema.const)})`;
  }
  if ("enum" in schema) {
    return `z.enum(${JSON.stringify(schema.enum)})`;
  }
  if (!("type" in schema)) {
    return `z.union([${schema.oneOf.map(toZodExpression).join(", ")}])`;
  }
  if (schema.type === "string") {
    return "z.string()";
  }
  if (schema.type === "integer") {
    return schema.minimum === 0 ? "z.number().int().nonnegative()" : "z.number().int()";
  }
  if (schema.type === "array") {
    const items = `z.array(${toZodExpression(schema.items)})`;
    return schema.maxItems === undefined ? items : `${items}.max(${schema.maxItems})`;
  }

  const strict = schema.additionalProperties === false || schema.unevaluatedProperties === false;
  const ownRequired = schema.required ?? [];

  if (schema.oneOf) {
    // Sibling `type: "object"` + `oneOf`: the outer required/strict keywords
    // apply to every branch (JSON Schema implicit-AND composition).
    const branches = schema.oneOf.map((branch) =>
      objectExpression(
        { ...schema.properties, ...branch.properties },
        [...ownRequired, ...(branch.required ?? [])],
        strict,
      ),
    );
    return `z.union([${branches.join(", ")}])`;
  }

  return objectExpression(schema.properties ?? {}, ownRequired, strict);
}

export function generateContractModule(root: { oneOf: readonly JsonSchema[] }): string {
  const exports = root.oneOf
    .map((branch) => `export const ${branchName(branch)}Schema = ${toZodExpression(branch)};`)
    .join("\n\n");

  return `// Generated by scripts/generate-contracts.ts from packages/contracts/source.json — do not edit by hand.\nimport { z } from "zod";\n\n${exports}\n`;
}

function isRecord(value: JsonSchema): value is Extract<JsonSchema, { type: "object" }> {
  return "type" in value && value.type === "object";
}

/**
 * Compares two object-shaped branches for admin-dashboard/v1 compatibility.
 * Additive optional fields stay v1-compatible; removed required fields or a
 * changed field type/shape are breaking and require a new contract version.
 */
export function assessCompatibility(previous: JsonSchema, candidate: JsonSchema): "compatible" | "breaking" {
  if (!isRecord(previous) || !isRecord(candidate)) {
    return JSON.stringify(previous) === JSON.stringify(candidate) ? "compatible" : "breaking";
  }

  const previousRequired = new Set(previous.required ?? []);
  for (const key of previousRequired) {
    if (!(candidate.required ?? []).includes(key)) {
      return "breaking";
    }
  }

  for (const [key, previousField] of Object.entries(previous.properties ?? {})) {
    const candidateField = (candidate.properties ?? {})[key];
    if (candidateField === undefined) {
      return "breaking";
    }
    if (assessCompatibility(previousField, candidateField) === "breaking") {
      return "breaking";
    }
  }

  return "compatible";
}
